import {
  HeartHandshake,
  FileBadge,
  Compass,
  HardHat,
  LandPlot,
  HandHelping,
  TreePine,
  Wallet,
  Megaphone,
  PieChart,
  Calculator,
  UserCheck,
  Palmtree,
  Monitor,
  Smile,
  Sprout,
  Siren,
  ShieldAlert,
  Stethoscope,
  Flame,
  Briefcase,
  LucideIcon,
} from 'lucide-react';

// 1. Map the slugs to specific Lucide icons
export const officeIcons: Record<string, LucideIcon> = {
  gad: HeartHandshake,
  'local-civil-registry-office': FileBadge,
  'municipal-planning-and-development-office': Compass,
  'municipal-engineering-office': HardHat,
  'municipal-assessors-office': LandPlot,
  'municipal-social-welfare-development-office': HandHelping,
  'municipal-environment-and-natural-resources-office': TreePine,
  'municipal-treasurers-office': Wallet,
  'public-information-office': Megaphone,
  'municipal-budget-office': PieChart,
  'municipal-accounting-office': Calculator,
  'municipal-human-resource-management-office': UserCheck,
  'municipal-tourism-office': Palmtree,
  'information-and-communication-systems-office': Monitor,
  'local-youth-and-development-office': Smile,
  'municipal-agriculture-office': Sprout,
  'municipal-mdrrmo-office': Siren,
  'municipal-police-station': ShieldAlert,
  'municipal-health-office': Stethoscope,
  'bureau-fire-protection': Flame,
  'business-permit-and-licensing-office': Briefcase,
};
